[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

########################################
# COMFYUI
########################################

[program:comfyui]
command=/opt/comfy-env/bin/python /app/ComfyUI/main.py --enable-manager --listen 0.0.0.0 --port 8188
directory=/app/ComfyUI

autostart=true
autorestart=true
startsecs=5
startretries=10

stopasgroup=true
killasgroup=true

stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

environment=HF_HOME="/workspace/huggingface",TORCH_HOME="/workspace/.cache/torch",XDG_CACHE_HOME="/workspace/.cache",TRITON_CACHE_DIR="/workspace/.triton",TORCHINDUCTOR_CACHE_DIR="/workspace/.cache/torch",COMFYUI_DISABLE_SEARCH="1",COMFYUI_DISABLE_AUTOLOAD="1",COMFYUI_CACHE_MODELS="1",COMFYUI_LAZY_LOAD="1",CUDA_MODULE_LOADING="LAZY",PYTORCH_CUDA_ALLOC_CONF="max_split_size_mb:512,garbage_collection_threshold:0.8"

########################################
# OSTRIS AI TOOLKIT UI
########################################

[program:ostris-ui]
command=/usr/bin/env pnpm start --port 8675
directory=/app/ai-toolkit/ui

autostart=true
autorestart=true
startsecs=5
startretries=10

stopasgroup=true
killasgroup=true

stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

########################################
# JUPYTER LAB
########################################

[program:jupyter]
command=/opt/comfy-env/bin/jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --ServerApp.token='' --ServerApp.password='' --ServerApp.allow_origin='*' --ServerApp.trust_xheaders=True --ServerApp.allow_remote_access=True --ServerApp.disable_check_xsrf=True
directory=/workspace

autostart=true
autorestart=true
startsecs=5
startretries=10

stopasgroup=true
killasgroup=true

stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0